name: Deploy to FTP

on:
  push:
    branches:
      - main  # Trigger deployment when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Set up FTP deployment
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./target  # Path to the directory you want to upload (e.g., build output)
          server-dir: /path/on/ftp/server  # Path where you want to upload files on your FTP server
